"""add response

Revision ID: 486f447a4ff6
Revises: f49ec490ea9a
Create Date: 2026-10-06 15:56:07.813879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486f447a4ff6'
down_revision = 'f49ec490ea9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('happy', sa.String(length=30), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('happy')

    # ### end Alembic commands ###
