"""remove happy

Revision ID: ac87e49c3e9f
Revises: 486f447a4ff6
Create Date: 2026-10-06 16:12:03.197476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac87e49c3e9f'
down_revision = '486f447a4ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('happy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('happy', sa.VARCHAR(length=30), nullable=True))

    # ### end Alembic commands ###
